#Dibujar dos árboles uno al lado del otro.
#separacion = '\t' + '\t'
#print("    *","    *", sep=separacion)
#print("   * *","   * *", sep=separacion)
#print("  *   *","  *   *", sep=separacion)
#print(" *     *"," *     *", sep='\t')
#print("***   ***","***   ***", sep='\t')
#print("  *   *", "  *   *", sep=separacion)
#print("  *   *", "  *   *", sep=separacion)
#print("  *****", "  *****", sep=separacion)
#print("    *" * 2)
print("    *    " * 2)
print("   * *   " * 2)
print("  *   *  " * 2)
print(" *     * " * 2)
print("***   ***" * 2)
print("  *   *  " * 2)
print("  *   *  " * 2)
print("  *****  " * 2)